import fs from "fs";

export type UpgradeStatus = "Updated" | "Merged" | "Skipped" | "Error";

export class AuditLogger {
  constructor(private filePath: string) {}

  async init(currentVersion: string, targetVersion: string, backupPath: string): Promise<void> {
    const content = `# Upgrade Audit Log: ${currentVersion} -> ${targetVersion}

Backup created at: 
${backupPath}
Date: ${new Date().toLocaleString()}

## File Progress

| File | Status | Notes |
| :--- | :--- | :--- |
`;
    fs.writeFileSync(this.filePath, content);
  }

  async logEntry(file: string, status: UpgradeStatus, notes: string): Promise<void> {
    const statusText = status === "Updated" || status === "Merged" ? `[x] ${status}` : `[ ] ${status}`;
    const entry = `| ${file} | ${statusText} | ${notes} |
`;
    fs.appendFileSync(this.filePath, entry);
  }

  async finalize(processedCount: number, errorCount: number): Promise<void> {
    const summary = `
## Summary

- Total Files Processed: ${processedCount}
- Errors Encountered: ${errorCount}
- Completed at: ${new Date().toLocaleString()}

---
*This log was automatically generated by the Geminisidian Upgrade System.*
`;
    fs.appendFileSync(this.filePath, summary);
  }
}
